In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cpu


## Introduction to Tensors

### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

#Tensors are make with .tensor

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
TENSOR = torch.tensor([[[1, 3, 4],
                        [3, 5, 6],
                        [3, 5, 5]]])
TENSOR

tensor([[[1, 3, 4],
         [3, 5, 6],
         [3, 5, 5]]])

In [12]:
TENSOR = torch.tensor([[[1, 3, 4],
                        [3, 5, 6],
                        [3, 5, 5]]])

### Random tensors



In [13]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4418, 0.2835, 0.6435, 0.6810],
        [0.7454, 0.9500, 0.7317, 0.2662],
        [0.0498, 0.3930, 0.7398, 0.7537]])

In [14]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.3353, 0.7007, 0.3474, 0.5414],
        [0.7933, 0.2032, 0.6186, 0.2165],
        [0.3214, 0.6191, 0.6535, 0.0364]])

In [15]:
float_16_tensor = torch.tensor([3, 5, 9], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [16]:
tensor = torch.tensor([1, 3, 4])
tensor.shape

torch.Size([3])

In [17]:
torch.matmul(tensor, tensor)

tensor(26)

In [18]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [19]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=8) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 2.2595,  1.2380, -0.1997,  0.6665, -0.7400,  0.7964,  0.4267,  0.6104],
        [ 4.5145,  2.2058, -0.2241,  0.8086, -0.5308,  2.2903,  1.6631,  1.0926],
        [ 6.7696,  3.1736, -0.2486,  0.9506, -0.3216,  3.7842,  2.8995,  1.5748]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 8])


In [20]:
x = torch.arange(0, 95, 10)

In [21]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [23]:
tensor = tensor.type(torch.float16)

In [24]:
tensor.dtype

torch.float16

In [25]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [26]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [27]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [28]:
!nvidia-smi

Sun Sep 14 20:24:22 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.29                 Driver Version: 581.29         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti   WDDM  |   00000000:07:00.0  On |                  N/A |
|  0%   46C    P0             56W /  240W |     632MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [29]:
torch.cuda.is_available()

False

In [30]:
print(torch.version.cuda)

None
